name: CI

on: [push, pull_request]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [
          "3.12"
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          [ -f ./requirements.txt ] && pip install -r ./requirements.txt || echo "No requirements.txt found"
          [ -f ./test-requirements.txt ] && pip install -r ./test-requirements.txt || echo "No test-requirements.txt found"
      - name: Run unittests
        run: |
          coverage run -m xmlrunner -o ./xmlunit

      - name: Prepare coverage reports
        run: |
          coverage report -m
          coverage html
          coverage xml

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: htmlcov
          path: htmlcov/

      - name: Publish coverage reports
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: matrix.os == 'ubuntu-latest'
        with:
          filename: ./**/coverage.xml
          badge: true
          format: markdown
          output: both

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main

      #todo add upload test report

      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: unittest
          path: ./xmlunit/TEST-*.xml    # Path to test results
          reporter: java-junit        # Format of test results